apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: data-server
  name: data-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: data-server
    spec:
      containers:
        - command:
            - ./run.sh
          env:
            - name: DATA_SERVER_HOST
              value: aaccdf7459ce842799e4615ad4920589-278800391.us-east-2.elb.amazonaws.com:8081
            - name: DSTU2_HOST
              value: abfa04c7dd6d043bbac4b501bbf6f636-613908026.us-east-2.elb.amazonaws.com:9002
            - name: DSTU3_HOST
              value: ab43880e82eaa48c4be0375f46146740-179423386.us-east-2.elb.amazonaws.com:9007
            - name: PORT
              value: "8081"
            - name: UI_HOST
              value: a249c63fbfb6648f28885723df6d7e85-1760505354.us-east-2.elb.amazonaws.com
          image: {{ .Values.image.dataServer.repository }}
          imagePullPolicy: {{ .Values.image.dataServer.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://aaccdf7459ce842799e4615ad4920589-278800391.us-east-2.elb.amazonaws.com:8081/data/manifest
          name: data-server
          ports:
            - containerPort: 8081
          resources: {}
          workingDir: /discovery-data-server
      restartPolicy: Always
status: {}
