apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: {{ .Values.image.web.repository }}
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          livenessProbe:
            initialDelaySeconds: 60
            exec:
              command:
                - curl
                - -f
                - http://a249c63fbfb6648f28885723df6d7e85-1760505354.us-east-2.elb.amazonaws.com
          name: web
          resources: {}
#          volumeMounts:
#            - mountPath: /discovery-web-ui/src
#              name: web-claim0
          workingDir: /discovery-web-ui
      restartPolicy: Always
#      volumes:
#        - name: web-claim0
#          persistentVolumeClaim:
#            claimName: web-claim0
#          hostPath:
#            path: "$(pwd)/discovery-web-ui/src" # absolute path from the host
#            type: Directory
status: {}
